# Generated by Django 2.2.3 on 2019-07-31 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('arrived_ts', models.DateTimeField()),
                ('weight_kg', models.IntegerField()),
                ('from_country', models.CharField(max_length=255)),
                ('to_country', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'nagel_shipment',
            },
        ),
    ]
